/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TeamAssigment1;

/*
Ricki Fernando Hutagaol
Ardhina Mulia Ariyanto
Kevin Sanjay Sirait
Angga Prasetya Budi
Caesari Hidayatun Nurrohmah
*/


import java.util.Scanner;

public class App {
    public static void main(String[] args) {
       Scanner input= new Scanner(System.in);
       int jumlah_orang;
       String namapemesan;
       double harganasgor=9999.99;
       double hargaayambakar=12345.67;
       double hargasteak= 21108.40;
       double hargaKwetiaw = 13579.13;
       double hargakambing=98765.43;
     
       System.out.println("----------Selamat Datang di restoran bungar---------");
       System.out.println("Pesanan untuk berapa orang? ");
       jumlah_orang=input.nextInt();
       System.out.println("Pesanan atas nama? ");
       namapemesan=input.nextLine();
       input.nextLine();
       System.out.println("Menu Spesial Hari ini");
       System.out.println("-----------------------");
       System.out.println("1.	Nasi Goreng Spesial    " + harganasgor);
       System.out.println("2.	Ayam Bakar  Spesial    " + hargaayambakar);
       System.out.println("3.	Steak Sirloin          " + hargasteak);
       System.out.println("4.	Kwetiaw  Siram         " + hargaKwetiaw);
       System.out.println("5.	Kambing Guling Spesial " + hargakambing);       
       System.out.println("Masukkan Pesanan Anda");  
       System.out.println("Nasi Goreng Spesial ");     
       int a = input.nextInt();
       double harga1=a*harganasgor;
       System.out.println("Ayam Bakar Spesial  ");     
       int b = input.nextInt();
       double harga2=b*hargaayambakar;
       System.out.println("Steak Sirloin ");     
       int c = input.nextInt();
       double harga3=c*hargasteak;
       System.out.println("Kwetiaw Siram");     
       int d = input.nextInt();
       double harga4=d*hargaKwetiaw;       
       System.out.println("Kambing Guling Spesial");     
       int e = input.nextInt();
       double harga5=e*hargakambing;
       double total=harga1+harga2+harga3+harga4+harga5;
       double diskon=(total*10)/100;
       double TotalBayar=total-diskon;
       double pembayaranperorang=TotalBayar/jumlah_orang;
       System.out.println("Selamat Siang ");
       System.out.println("Pesanan untuk berapa orang " + jumlah_orang);
       System.out.println("Pesanan atas nama " + namapemesan);
       System.out.println("Menu Spesial Hari ini");
       System.out.println("=====================");
       System.out.println("Pesanan Anda [batas pesanan 0-10 porsi");
       System.out.println("1.    Nasi Ayam Goreng Spesial         "  + a );
       System.out.println("2.    Ayam Bakar Spesial               "  + b );
       System.out.println("3.    Steak Sirloin Spesial            "  + c );
       System.out.println("4.    Kwetiaw Siram                    "  + d );
       System.out.println("5.    Kambing Guling Spesial           "  + d );
       System.out.println("    Selamat menikmati makanan anda   ");
       System.out.println("Pembelian :");
       System.out.println("1.    Nasi Ayam Goreng Spesial     "  + a +" Porsi *"+ harganasgor+"=Rp. "+harga1 );
       System.out.println("2.    Ayam Bakar Spesial           "  + b +" Porsi *"+ hargaayambakar+"=Rp. " +harga2);
       System.out.println("3.    Steak Sirloin Spesial        "  + c +" Porsi *"+ hargasteak+"=Rp.  "+harga3);
       System.out.println("4.    Kwetiaw Siram                "  + d +" Porsi *"+ hargaKwetiaw+"=Rp.  "+harga4);
       System.out.println("5.    Kambing Guling Spesial       "  + d +" Porsi *"+ hargakambing+"=Rp.  "+harga5);
       System.out.println("----------------------------------------------------------------------------------");
       System.out.println("Total Pembelian                                                      ="+total);
       System.out.println("Diskon (10%) <Masa Promosi>                                          ="+diskon);
       System.out.println("----------------------------------------------------------------------------------");
       System.out.println("Total Pembelian Setelah Diskon                                       ="+TotalBayar);       
       System.out.println("Total Pembelian per orang                                            ="+pembayaranperorang);  
       
       System.out.println("--------------Terima Kasih Atas Kunjungan Anda-----------------");
    
        
        
    }    
}
